Cheque/Cheque/Controllers/TempModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HouseFly.Models;
using HouseFly.Context;

namespace HouseFly.Controllers
{
    public class TempModelsController : Controller
    {
      
        private TempContext db = new TempContext();

        // GET: TempModels
        public ActionResult Index()
        {
            return View(db.TempModels.ToList());
        }

        // GET: TempModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TempModels tempModels = db.TempModels.Find(id);
            if (tempModels == null)
            {
                return HttpNotFound();
            }
            return View(tempModels);
        }

        // GET: TempModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TempModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TempId,Domain,Temp,Pressure,Humidity,TimeStamp")] TempModels tempModels)
        {
            if (ModelState.IsValid)
            {
                db.TempModels.Add(tempModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tempModels);
        }

        public void CreateInternal(TempModels tempModels)
        {
            if (ModelState.IsValid)
            {
                db.TempModels.Add(tempModels);
                db.SaveChanges();
            }
        }

        // GET: TempModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TempModels tempModels = db.TempModels.Find(id);
            if (tempModels == null)
            {
                return HttpNotFound();
            }
            return View(tempModels);
        }

        // POST: TempModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TempId,Domain,Temp,Pressure,Humidity,TimeStamp")] TempModels tempModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tempModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tempModels);
        }

        // GET: TempModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TempModels tempModels = db.TempModels.Find(id);
            if (tempModels == null)
            {
                return HttpNotFound();
            }
            return View(tempModels);
        }

        // POST: TempModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TempModels tempModels = db.TempModels.Find(id);
            db.TempModels.Remove(tempModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cheque/Cheque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <script src="@Url.Content("~/Scripts/helpers.js")" type="text/javascript"></script>
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HouseFly</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img src="~/lightgreyfly.png" width="25" height="25" title="HouseFly" />
                </a>
                @Html.ActionLink("HouseFly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">


                <ul class="nav navbar-nav">

                   
                    @if (Request.IsAuthenticated)
                    {
                        if (User.Identity.Name == "adamdthomas@gmail.com")
                        {
                            <li>@Html.ActionLink("Garage", "Dashboard", "Home")</li>
                            <li>@Html.ActionLink("Porch", "Porch", "Home")</li>
                            <li>@Html.ActionLink("Video", "Video", "Home")</li>
                            <li>@Html.ActionLink("Weather", "Index", "TempModels")</li>
                            <li>@Html.ActionLink("Sandbox", "Sandbox", "Home")</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Thomas Workshop Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>